kind: Pod
apiVersion: v1
metadata:
  name: testpod2
  annotations:
    description: My second pod is going to be created
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-John; sleep 5 ; done"]
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Jerry; sleep 5 ; done"]
  restartPolicy: Never
