kind: Pod
apiVersion: v1
metadata:
  name: environments
  annotations:
    description: Environmrnt variable in pod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Johny; sleep 5 ; done"]
      env:
       - name: MYNAME
         value: JOHNY
